# This workflow will build and push a node.js application to an Azure Web App on every push to the master branch.
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
#
# 2. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Update HLD Repository
    runs-on: ubuntu-latest
    steps:
    - name: git-bash
      uses: fnkr/github-action-git-bash@v1.1
    - name: Download and run release script
      run: | 
        curl https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/build.sh > build.sh
        chmod +x ./build.sh
        curl https://raw.githubusercontent.com/Microsoft/bedrock/master/gitops/azure-devops/release.sh > release.sh
        chmod +x ./release.sh
        bash release.shx
      env:
        FAB_ENV_NAME: DEV
        SUBCOMPONENT: apis.githubmigrator-git-clone-service
        ACCESS_TOKEN_SECRET: ${{ secrets.HLD_ACCESS_TOKEN }}
        COMMIT_MESSAGE: Update image to ${{ github.sha }}
        REPO: https://github.com/microsoft-1es/github-integration-hld
        YAML_PATH: image.tag
        YAML_PATH_VALUE: ${{ github.sha }}
    - name: Test
      if: failure()
      run: echo "test"
